"""Changed attribute posted to date_posted

Revision ID: e3a213aa5f81
Revises: c2ab7df3d5f5
Create Date: 2019-02-16 09:55:08.359304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3a213aa5f81'
down_revision = 'c2ab7df3d5f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('data_posted', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('posted', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'data_posted')
    # ### end Alembic commands ###
